# Generated by Django 4.2.13 on 2024-07-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giveaid', '0004_unregistereddonation_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='successstory',
            name='image',
            field=models.ImageField(null=True, upload_to='success_stories/images/'),
        ),
        migrations.AddField(
            model_name='successstory',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='success_stories/videos/'),
        ),
        migrations.AddField(
            model_name='userdonation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userdonation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
    ]
